apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-health-component
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-health-component
  template:
    metadata:
      labels:
        app: insurance-health-component
    spec:
      containers:
      - name: insurance-health-component
        image: prema064/insurance-health-component:87
        ports:
        - containerPort: 9080
