apiVersion: v1
kind: Service
metadata:
  name: insurance-health-component-service
spec:
  type: NodePort
  selector:
    app: insurance-health-component
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9080
      nodePort: 30080